plugins {
    id 'com.android.application'
}

android {
    namespace 'com.johndsdev.androidnav'
    compileSdk 35

    signingConfigs {
        debugPersistent {
            storeFile file("$rootDir/signing/androidnav-debug.keystore")
            storePassword 'androidnav'
            keyAlias 'androidnav'
            keyPassword 'androidnav'
            v1SigningEnabled true
            v2SigningEnabled true
            v3SigningEnabled true
            v4SigningEnabled true
        }
    }

    defaultConfig {
        applicationId 'com.johndsdev.androidnav.navidrome'
        minSdk 23
        targetSdk 34
        versionCode 2
        versionName '2.0'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debugPersistent
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
